site_name: OBO Templates and Design Pattern Library
theme: readthedocs
nav:
  - Getting started: index.md
  - How-to guides:
      - Overview: howto.md
  - Tutorials:
      - Overview: tutorials.md
  - Key topics:
    - Overview: key-topics.md
    - Taxon constraints: key-topics/taxon_constraints.md
    - Characteristics: key-topics/characteristics.md
  - Reference:
    - DOSDP templates:
      - Core templates: reference/dosdp_templates.md
      - OBO Browser: reference/dosdp_browser.md
      - Templates:
        - Example: reference/dosdp/placeholder.md
    - ROBOT templates:
      - Overview: reference/robot_templates.md
      - OBO Browser: reference/robot_template_browser.md
      - Templates:
        - Example: reference/robot_template/placeholder.md


